#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CaenRfIdSample.Droid.Resource", IsApplication=true)]

namespace CaenRfIdSample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int LinkProfile = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int RWBank = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int Session = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int TagsTest = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int lockActionArray = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int lockBankArray = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int mWViewMode = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int supported_reader_name = 2131034115;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int green = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int red = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int yellow = 2131099649;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int default_margin = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int group_margin = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int padding_large = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int padding_medium = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int padding_small = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int rt0005_mk_sl_value = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int rt0005alarmlabel = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int rt0005temperature = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int statistic_margin = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int table_margin = 2131165187;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int banner = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int batteria_bassa = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int batteria_carica = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int batteria_scarica = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int default_border = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int file = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int folder = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_action_search = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_bt_reader = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_ec_launcher = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_launcher = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_menu_add = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_menu_back = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_menu_background = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_menu_block = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_menu_close_clear_cancel = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_menu_delete = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_menu_edit = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_menu_forward = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_menu_help = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_menu_manage = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_menu_play_clip = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_menu_preferences = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_menu_refresh = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_menu_revert = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_menu_save = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_menu_stop = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_tab_antenna = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_tab_protocol = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_tab_reader_conf = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_tab_selected_antenna = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_tab_selected_preference = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_tab_selected_proto = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_tab_selected_reader_conf = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_tab_unselected_antenna = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_tab_unselected_preference = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_tab_unselected_proto = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_tab_unselected_reader_conf = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_tcp_reader = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int Icon = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int led_rosso = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int led_verde = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int up_folder = 2130837546;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0009
			public const int RelativeLayout1 = 2131361801;
			
			// aapt resource value: 0x7f0a0016
			public const int add_reader_button = 2131361814;
			
			// aapt resource value: 0x7f0a0014
			public const int banner = 2131361812;
			
			// aapt resource value: 0x7f0a0002
			public const int bt_selection_list = 2131361794;
			
			// aapt resource value: 0x7f0a000b
			public const int command_layout = 2131361803;
			
			// aapt resource value: 0x7f0a000a
			public const int imageView1 = 2131361802;
			
			// aapt resource value: 0x7f0a0003
			public const int info_text = 2131361795;
			
			// aapt resource value: 0x7f0a0006
			public const int inventory_item = 2131361798;
			
			// aapt resource value: 0x7f0a0008
			public const int inventory_item_antenna = 2131361800;
			
			// aapt resource value: 0x7f0a0005
			public const int inventory_item_container = 2131361797;
			
			// aapt resource value: 0x7f0a0007
			public const int inventory_item_counter = 2131361799;
			
			// aapt resource value: 0x7f0a000f
			public const int inventory_list = 2131361807;
			
			// aapt resource value: 0x7f0a0004
			public const int inventorybutton = 2131361796;
			
			// aapt resource value: 0x7f0a000c
			public const int linearLayout1 = 2131361804;
			
			// aapt resource value: 0x7f0a0010
			public const int list_reader = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int reader_image = 2131361809;
			
			// aapt resource value: 0x7f0a0013
			public const int reader_info = 2131361811;
			
			// aapt resource value: 0x7f0a0015
			public const int reader_list = 2131361813;
			
			// aapt resource value: 0x7f0a0012
			public const int reader_name = 2131361810;
			
			// aapt resource value: 0x7f0a0001
			public const int search_label = 2131361793;
			
			// aapt resource value: 0x7f0a0000
			public const int search_progress_bar = 2131361792;
			
			// aapt resource value: 0x7f0a000d
			public const int total_found = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int total_found_num = 2131361806;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080001
			public const int max_notes_line = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int pwd_hex_char = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int bt_selection = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int bt_selection_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int device_name = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int inventory = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int inventory_row = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int inventory_selection = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int list_reader = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int main = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040070
			public const int Inventory_mode_rssi_checkbox = 2130968688;
			
			// aapt resource value: 0x7f04007d
			public const int _0 = 2130968701;
			
			// aapt resource value: 0x7f040086
			public const int accessDenied = 2130968710;
			
			// aapt resource value: 0x7f040003
			public const int add_reader_button = 2130968579;
			
			// aapt resource value: 0x7f04001f
			public const int antenna_four_checkbox = 2130968607;
			
			// aapt resource value: 0x7f04002d
			public const int antenna_green_note = 2130968621;
			
			// aapt resource value: 0x7f04002b
			public const int antenna_instruction = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int antenna_note = 2130968620;
			
			// aapt resource value: 0x7f04001c
			public const int antenna_one_checkbox = 2130968604;
			
			// aapt resource value: 0x7f04002f
			public const int antenna_red_note = 2130968623;
			
			// aapt resource value: 0x7f04001e
			public const int antenna_three_checkbox = 2130968606;
			
			// aapt resource value: 0x7f04001d
			public const int antenna_two_checkbox = 2130968605;
			
			// aapt resource value: 0x7f04002e
			public const int antenna_yellow_note = 2130968622;
			
			// aapt resource value: 0x7f04001b
			public const int antennae_selection_label = 2130968603;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040018
			public const int apply = 2130968600;
			
			// aapt resource value: 0x7f040038
			public const int ascii_label = 2130968632;
			
			// aapt resource value: 0x7f040071
			public const int banner = 2130968689;
			
			// aapt resource value: 0x7f040037
			public const int beep_label = 2130968631;
			
			// aapt resource value: 0x7f040008
			public const int bt_selection_title = 2130968584;
			
			// aapt resource value: 0x7f04000f
			public const int caen_rfid_srl = 2130968591;
			
			// aapt resource value: 0x7f040081
			public const int cancelButtonText = 2130968705;
			
			// aapt resource value: 0x7f040082
			public const int cannotSaveFileMessage = 2130968706;
			
			// aapt resource value: 0x7f04000e
			public const int clear_button = 2130968590;
			
			// aapt resource value: 0x7f040034
			public const int color_pick_label = 2130968628;
			
			// aapt resource value: 0x7f040036
			public const int color_picker_button = 2130968630;
			
			// aapt resource value: 0x7f04008a
			public const int createButtonText = 2130968714;
			
			// aapt resource value: 0x7f04000d
			public const int current_found = 2130968589;
			
			// aapt resource value: 0x7f040007
			public const int default_ip = 2130968583;
			
			// aapt resource value: 0x7f04006f
			public const int easy_controller_products_description = 2130968687;
			
			// aapt resource value: 0x7f04007f
			public const int enterFileName = 2130968703;
			
			// aapt resource value: 0x7f040083
			public const int fileNameFirstMessage = 2130968707;
			
			// aapt resource value: 0x7f04008c
			public const int folderCreationError = 2130968716;
			
			// aapt resource value: 0x7f04008b
			public const int folderCreationOk = 2130968715;
			
			// aapt resource value: 0x7f040030
			public const int green = 2130968624;
			
			// aapt resource value: 0x7f040002
			public const int hello = 2130968578;
			
			// aapt resource value: 0x7f040050
			public const int hello_world = 2130968656;
			
			// aapt resource value: 0x7f04008d
			public const int information = 2130968717;
			
			// aapt resource value: 0x7f040009
			public const int inventory_button_start = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int inventory_button_stop = 2130968586;
			
			// aapt resource value: 0x7f040039
			public const int inventory_mode_item = 2130968633;
			
			// aapt resource value: 0x7f04003c
			public const int inventory_mode_mask_checkbox = 2130968636;
			
			// aapt resource value: 0x7f04003a
			public const int inventory_mode_title = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int inventory_mode_trigger = 2130968635;
			
			// aapt resource value: 0x7f04006d
			public const int kill_tag_kill_button = 2130968685;
			
			// aapt resource value: 0x7f04006e
			public const int kill_tag_pwd_label = 2130968686;
			
			// aapt resource value: 0x7f04006c
			public const int kill_tag_title = 2130968684;
			
			// aapt resource value: 0x7f040017
			public const int lbt_checkbox_label = 2130968599;
			
			// aapt resource value: 0x7f040001
			public const int library_version = 2130968577;
			
			// aapt resource value: 0x7f040085
			public const int loadButtonText = 2130968709;
			
			// aapt resource value: 0x7f040068
			public const int lock_tag_accesspwd_label = 2130968680;
			
			// aapt resource value: 0x7f040063
			public const int lock_tag_action_label = 2130968675;
			
			// aapt resource value: 0x7f040064
			public const int lock_tag_apply_button = 2130968676;
			
			// aapt resource value: 0x7f040062
			public const int lock_tag_bank_label = 2130968674;
			
			// aapt resource value: 0x7f040067
			public const int lock_tag_killpwd_label = 2130968679;
			
			// aapt resource value: 0x7f040065
			public const int lock_tag_pwd_label = 2130968677;
			
			// aapt resource value: 0x7f040066
			public const int lock_tag_setpwd_button = 2130968678;
			
			// aapt resource value: 0x7f040069
			public const int lock_tag_setpwd_label = 2130968681;
			
			// aapt resource value: 0x7f04006a
			public const int lock_tag_setpwd_note = 2130968682;
			
			// aapt resource value: 0x7f040061
			public const int lock_tag_title = 2130968673;
			
			// aapt resource value: 0x7f04003d
			public const int mask_option_label = 2130968637;
			
			// aapt resource value: 0x7f04001a
			public const int max_power = 2130968602;
			
			// aapt resource value: 0x7f040051
			public const int menu_settings = 2130968657;
			
			// aapt resource value: 0x7f040019
			public const int min_power = 2130968601;
			
			// aapt resource value: 0x7f040023
			public const int minus = 2130968611;
			
			// aapt resource value: 0x7f040087
			public const int missingFile = 2130968711;
			
			// aapt resource value: 0x7f040015
			public const int modulation_label = 2130968597;
			
			// aapt resource value: 0x7f040088
			public const int newFolderButtonText = 2130968712;
			
			// aapt resource value: 0x7f040089
			public const int newFolderDialogMessage = 2130968713;
			
			// aapt resource value: 0x7f040084
			public const int okButtonText = 2130968708;
			
			// aapt resource value: 0x7f040022
			public const int plus = 2130968610;
			
			// aapt resource value: 0x7f040013
			public const int power_label = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int preferences_item = 2130968594;
			
			// aapt resource value: 0x7f040035
			public const int preferences_title = 2130968629;
			
			// aapt resource value: 0x7f040048
			public const int program_id_button = 2130968648;
			
			// aapt resource value: 0x7f04004a
			public const int program_id_note = 2130968650;
			
			// aapt resource value: 0x7f040049
			public const int program_id_title = 2130968649;
			
			// aapt resource value: 0x7f04004b
			public const int program_tag_ascii_input_checkbox = 2130968651;
			
			// aapt resource value: 0x7f04004e
			public const int program_tag_force_id = 2130968654;
			
			// aapt resource value: 0x7f04004c
			public const int program_tag_password_label = 2130968652;
			
			// aapt resource value: 0x7f04004d
			public const int program_tag_password_note = 2130968653;
			
			// aapt resource value: 0x7f04004f
			public const int program_tag_selected_tag_label = 2130968655;
			
			// aapt resource value: 0x7f040020
			public const int protocol_configuration_label = 2130968608;
			
			// aapt resource value: 0x7f040024
			public const int q_description = 2130968612;
			
			// aapt resource value: 0x7f040021
			public const int q_parameter = 2130968609;
			
			// aapt resource value: 0x7f040055
			public const int read_and_write_activity = 2130968661;
			
			// aapt resource value: 0x7f040056
			public const int read_and_write_address_label = 2130968662;
			
			// aapt resource value: 0x7f04005e
			public const int read_and_write_ascii_input = 2130968670;
			
			// aapt resource value: 0x7f04005c
			public const int read_and_write_bank_label = 2130968668;
			
			// aapt resource value: 0x7f040058
			public const int read_and_write_bank_prompt = 2130968664;
			
			// aapt resource value: 0x7f040057
			public const int read_and_write_init_address_label = 2130968663;
			
			// aapt resource value: 0x7f04005d
			public const int read_and_write_note = 2130968669;
			
			// aapt resource value: 0x7f04005a
			public const int read_and_write_password_edittext = 2130968666;
			
			// aapt resource value: 0x7f04005b
			public const int read_and_write_password_label = 2130968667;
			
			// aapt resource value: 0x7f040059
			public const int read_and_write_read_button = 2130968665;
			
			// aapt resource value: 0x7f040054
			public const int read_and_write_title_label = 2130968660;
			
			// aapt resource value: 0x7f04005f
			public const int read_and_write_write_button = 2130968671;
			
			// aapt resource value: 0x7f040011
			public const int reader_configuration_item = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int reader_image = 2130968592;
			
			// aapt resource value: 0x7f040032
			public const int red = 2130968626;
			
			// aapt resource value: 0x7f04000b
			public const int refresh_button = 2130968587;
			
			// aapt resource value: 0x7f040079
			public const int rt0005_battery_status = 2130968697;
			
			// aapt resource value: 0x7f040072
			public const int rt0005_ctrl_room = 2130968690;
			
			// aapt resource value: 0x7f040075
			public const int rt0005_est_time_arrival = 2130968693;
			
			// aapt resource value: 0x7f040074
			public const int rt0005_histogram_alarm = 2130968692;
			
			// aapt resource value: 0x7f040078
			public const int rt0005_mean_kinetic_temp = 2130968696;
			
			// aapt resource value: 0x7f040076
			public const int rt0005_mem_full = 2130968694;
			
			// aapt resource value: 0x7f04007c
			public const int rt0005_refresh_state_button_caption = 2130968700;
			
			// aapt resource value: 0x7f040077
			public const int rt0005_rem_shelf_life = 2130968695;
			
			// aapt resource value: 0x7f04007a
			public const int rt0005_shipping_date = 2130968698;
			
			// aapt resource value: 0x7f04007b
			public const int rt0005_stop_date = 2130968699;
			
			// aapt resource value: 0x7f040073
			public const int rt0005taglabel = 2130968691;
			
			// aapt resource value: 0x7f040080
			public const int saveButtonText = 2130968704;
			
			// aapt resource value: 0x7f040027
			public const int session1_note = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int session2_note = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int session3_note = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int session4_note = 2130968618;
			
			// aapt resource value: 0x7f040026
			public const int session_description = 2130968614;
			
			// aapt resource value: 0x7f040033
			public const int session_note = 2130968627;
			
			// aapt resource value: 0x7f040025
			public const int session_parameter = 2130968613;
			
			// aapt resource value: 0x7f040047
			public const int start_byte_mask_label = 2130968647;
			
			// aapt resource value: 0x7f040045
			public const int target_ascii_mask_checkbox = 2130968645;
			
			// aapt resource value: 0x7f040044
			public const int target_both_match_radaiobutton = 2130968644;
			
			// aapt resource value: 0x7f04003f
			public const int target_by_mask_radiobutton = 2130968639;
			
			// aapt resource value: 0x7f04003e
			public const int target_by_select_tag_radiobutton = 2130968638;
			
			// aapt resource value: 0x7f040041
			public const int target_end_with_radiobutton = 2130968641;
			
			// aapt resource value: 0x7f040042
			public const int target_match_radiobutton = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int target_not_match_radiobutton = 2130968643;
			
			// aapt resource value: 0x7f040046
			public const int target_selected_ascii_checkbox = 2130968646;
			
			// aapt resource value: 0x7f040040
			public const int target_start_with_radiobutton = 2130968640;
			
			// aapt resource value: 0x7f040006
			public const int tcp_cancel = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int tcp_confirm = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int tcp_label = 2130968580;
			
			// aapt resource value: 0x7f04007e
			public const int titleFileDialog = 2130968702;
			
			// aapt resource value: 0x7f04006b
			public const int title_activity_kill_tag = 2130968683;
			
			// aapt resource value: 0x7f040060
			public const int title_activity_lock_tag = 2130968672;
			
			// aapt resource value: 0x7f040052
			public const int title_activity_main = 2130968658;
			
			// aapt resource value: 0x7f040053
			public const int title_activity_read_and__write = 2130968659;
			
			// aapt resource value: 0x7f040014
			public const int todo = 2130968596;
			
			// aapt resource value: 0x7f04000c
			public const int total_found = 2130968588;
			
			// aapt resource value: 0x7f040031
			public const int yellow = 2130968625;
			
			// aapt resource value: 0x7f040016
			public const int zero = 2130968598;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int inventory_button_style = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
