#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CaenRfIdSample.Droid.Resource", IsApplication=true)]

namespace CaenRfIdSample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040001
			public const int LinkProfile = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int RWBank = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int Session = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int TagsTest = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int lockActionArray = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int lockBankArray = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int mWViewMode = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int supported_reader_name = 2130968579;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int green = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int red = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int yellow = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int default_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int group_margin = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int padding_large = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int padding_medium = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int padding_small = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int rt0005_mk_sl_value = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int rt0005alarmlabel = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int rt0005temperature = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int statistic_margin = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int table_margin = 2131099651;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int banner = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int batteria_bassa = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int batteria_carica = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int batteria_scarica = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int default_border = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int file = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int folder = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_action_search = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_bt_reader = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_ec_launcher = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_launcher = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_menu_add = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_menu_back = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_menu_background = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_menu_block = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_menu_close_clear_cancel = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_menu_delete = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_menu_edit = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_menu_forward = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_menu_help = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_menu_manage = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_menu_play_clip = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_menu_preferences = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_menu_refresh = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_menu_revert = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_menu_save = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_menu_stop = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_tab_antenna = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_tab_protocol = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_tab_reader_conf = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_tab_selected_antenna = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_tab_selected_preference = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_tab_selected_proto = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_tab_selected_reader_conf = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_tab_unselected_antenna = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_tab_unselected_preference = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_tab_unselected_proto = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_tab_unselected_reader_conf = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_tcp_reader = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int Icon = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int led_rosso = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int led_verde = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int up_folder = 2130837546;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0009
			public const int RelativeLayout1 = 2131361801;
			
			// aapt resource value: 0x7f0a0016
			public const int add_reader_button = 2131361814;
			
			// aapt resource value: 0x7f0a0014
			public const int banner = 2131361812;
			
			// aapt resource value: 0x7f0a0002
			public const int bt_selection_list = 2131361794;
			
			// aapt resource value: 0x7f0a000b
			public const int command_layout = 2131361803;
			
			// aapt resource value: 0x7f0a000a
			public const int imageView1 = 2131361802;
			
			// aapt resource value: 0x7f0a0003
			public const int info_text = 2131361795;
			
			// aapt resource value: 0x7f0a0006
			public const int inventory_item = 2131361798;
			
			// aapt resource value: 0x7f0a0008
			public const int inventory_item_antenna = 2131361800;
			
			// aapt resource value: 0x7f0a0005
			public const int inventory_item_container = 2131361797;
			
			// aapt resource value: 0x7f0a0007
			public const int inventory_item_counter = 2131361799;
			
			// aapt resource value: 0x7f0a000f
			public const int inventory_list = 2131361807;
			
			// aapt resource value: 0x7f0a0004
			public const int inventorybutton = 2131361796;
			
			// aapt resource value: 0x7f0a000c
			public const int linearLayout1 = 2131361804;
			
			// aapt resource value: 0x7f0a0010
			public const int list_reader = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int reader_image = 2131361809;
			
			// aapt resource value: 0x7f0a0013
			public const int reader_info = 2131361811;
			
			// aapt resource value: 0x7f0a0015
			public const int reader_list = 2131361813;
			
			// aapt resource value: 0x7f0a0012
			public const int reader_name = 2131361810;
			
			// aapt resource value: 0x7f0a0001
			public const int search_label = 2131361793;
			
			// aapt resource value: 0x7f0a0000
			public const int search_progress_bar = 2131361792;
			
			// aapt resource value: 0x7f0a000d
			public const int total_found = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int total_found_num = 2131361806;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070001
			public const int max_notes_line = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int pwd_hex_char = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int bt_selection = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int bt_selection_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int device_name = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int inventory = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int inventory_row = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int inventory_selection = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int list_reader = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int main = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f08006f
			public const int Inventory_mode_rssi_checkbox = 2131230831;
			
			// aapt resource value: 0x7f08007c
			public const int _0 = 2131230844;
			
			// aapt resource value: 0x7f080085
			public const int accessDenied = 2131230853;
			
			// aapt resource value: 0x7f080002
			public const int add_reader_button = 2131230722;
			
			// aapt resource value: 0x7f08001e
			public const int antenna_four_checkbox = 2131230750;
			
			// aapt resource value: 0x7f08002c
			public const int antenna_green_note = 2131230764;
			
			// aapt resource value: 0x7f08002a
			public const int antenna_instruction = 2131230762;
			
			// aapt resource value: 0x7f08002b
			public const int antenna_note = 2131230763;
			
			// aapt resource value: 0x7f08001b
			public const int antenna_one_checkbox = 2131230747;
			
			// aapt resource value: 0x7f08002e
			public const int antenna_red_note = 2131230766;
			
			// aapt resource value: 0x7f08001d
			public const int antenna_three_checkbox = 2131230749;
			
			// aapt resource value: 0x7f08001c
			public const int antenna_two_checkbox = 2131230748;
			
			// aapt resource value: 0x7f08002d
			public const int antenna_yellow_note = 2131230765;
			
			// aapt resource value: 0x7f08001a
			public const int antennae_selection_label = 2131230746;
			
			// aapt resource value: 0x7f080001
			public const int app_name = 2131230721;
			
			// aapt resource value: 0x7f080017
			public const int apply = 2131230743;
			
			// aapt resource value: 0x7f080037
			public const int ascii_label = 2131230775;
			
			// aapt resource value: 0x7f080070
			public const int banner = 2131230832;
			
			// aapt resource value: 0x7f080036
			public const int beep_label = 2131230774;
			
			// aapt resource value: 0x7f080007
			public const int bt_selection_title = 2131230727;
			
			// aapt resource value: 0x7f08000e
			public const int caen_rfid_srl = 2131230734;
			
			// aapt resource value: 0x7f080080
			public const int cancelButtonText = 2131230848;
			
			// aapt resource value: 0x7f080081
			public const int cannotSaveFileMessage = 2131230849;
			
			// aapt resource value: 0x7f08000d
			public const int clear_button = 2131230733;
			
			// aapt resource value: 0x7f080033
			public const int color_pick_label = 2131230771;
			
			// aapt resource value: 0x7f080035
			public const int color_picker_button = 2131230773;
			
			// aapt resource value: 0x7f080089
			public const int createButtonText = 2131230857;
			
			// aapt resource value: 0x7f08000c
			public const int current_found = 2131230732;
			
			// aapt resource value: 0x7f080006
			public const int default_ip = 2131230726;
			
			// aapt resource value: 0x7f08006e
			public const int easy_controller_products_description = 2131230830;
			
			// aapt resource value: 0x7f08007e
			public const int enterFileName = 2131230846;
			
			// aapt resource value: 0x7f080082
			public const int fileNameFirstMessage = 2131230850;
			
			// aapt resource value: 0x7f08008b
			public const int folderCreationError = 2131230859;
			
			// aapt resource value: 0x7f08008a
			public const int folderCreationOk = 2131230858;
			
			// aapt resource value: 0x7f08002f
			public const int green = 2131230767;
			
			// aapt resource value: 0x7f080000
			public const int hello = 2131230720;
			
			// aapt resource value: 0x7f08004f
			public const int hello_world = 2131230799;
			
			// aapt resource value: 0x7f08008c
			public const int information = 2131230860;
			
			// aapt resource value: 0x7f080008
			public const int inventory_button_start = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int inventory_button_stop = 2131230729;
			
			// aapt resource value: 0x7f080038
			public const int inventory_mode_item = 2131230776;
			
			// aapt resource value: 0x7f08003b
			public const int inventory_mode_mask_checkbox = 2131230779;
			
			// aapt resource value: 0x7f080039
			public const int inventory_mode_title = 2131230777;
			
			// aapt resource value: 0x7f08003a
			public const int inventory_mode_trigger = 2131230778;
			
			// aapt resource value: 0x7f08006c
			public const int kill_tag_kill_button = 2131230828;
			
			// aapt resource value: 0x7f08006d
			public const int kill_tag_pwd_label = 2131230829;
			
			// aapt resource value: 0x7f08006b
			public const int kill_tag_title = 2131230827;
			
			// aapt resource value: 0x7f080016
			public const int lbt_checkbox_label = 2131230742;
			
			// aapt resource value: 0x7f080084
			public const int loadButtonText = 2131230852;
			
			// aapt resource value: 0x7f080067
			public const int lock_tag_accesspwd_label = 2131230823;
			
			// aapt resource value: 0x7f080062
			public const int lock_tag_action_label = 2131230818;
			
			// aapt resource value: 0x7f080063
			public const int lock_tag_apply_button = 2131230819;
			
			// aapt resource value: 0x7f080061
			public const int lock_tag_bank_label = 2131230817;
			
			// aapt resource value: 0x7f080066
			public const int lock_tag_killpwd_label = 2131230822;
			
			// aapt resource value: 0x7f080064
			public const int lock_tag_pwd_label = 2131230820;
			
			// aapt resource value: 0x7f080065
			public const int lock_tag_setpwd_button = 2131230821;
			
			// aapt resource value: 0x7f080068
			public const int lock_tag_setpwd_label = 2131230824;
			
			// aapt resource value: 0x7f080069
			public const int lock_tag_setpwd_note = 2131230825;
			
			// aapt resource value: 0x7f080060
			public const int lock_tag_title = 2131230816;
			
			// aapt resource value: 0x7f08003c
			public const int mask_option_label = 2131230780;
			
			// aapt resource value: 0x7f080019
			public const int max_power = 2131230745;
			
			// aapt resource value: 0x7f080050
			public const int menu_settings = 2131230800;
			
			// aapt resource value: 0x7f080018
			public const int min_power = 2131230744;
			
			// aapt resource value: 0x7f080022
			public const int minus = 2131230754;
			
			// aapt resource value: 0x7f080086
			public const int missingFile = 2131230854;
			
			// aapt resource value: 0x7f080014
			public const int modulation_label = 2131230740;
			
			// aapt resource value: 0x7f080087
			public const int newFolderButtonText = 2131230855;
			
			// aapt resource value: 0x7f080088
			public const int newFolderDialogMessage = 2131230856;
			
			// aapt resource value: 0x7f080083
			public const int okButtonText = 2131230851;
			
			// aapt resource value: 0x7f080021
			public const int plus = 2131230753;
			
			// aapt resource value: 0x7f080012
			public const int power_label = 2131230738;
			
			// aapt resource value: 0x7f080011
			public const int preferences_item = 2131230737;
			
			// aapt resource value: 0x7f080034
			public const int preferences_title = 2131230772;
			
			// aapt resource value: 0x7f080047
			public const int program_id_button = 2131230791;
			
			// aapt resource value: 0x7f080049
			public const int program_id_note = 2131230793;
			
			// aapt resource value: 0x7f080048
			public const int program_id_title = 2131230792;
			
			// aapt resource value: 0x7f08004a
			public const int program_tag_ascii_input_checkbox = 2131230794;
			
			// aapt resource value: 0x7f08004d
			public const int program_tag_force_id = 2131230797;
			
			// aapt resource value: 0x7f08004b
			public const int program_tag_password_label = 2131230795;
			
			// aapt resource value: 0x7f08004c
			public const int program_tag_password_note = 2131230796;
			
			// aapt resource value: 0x7f08004e
			public const int program_tag_selected_tag_label = 2131230798;
			
			// aapt resource value: 0x7f08001f
			public const int protocol_configuration_label = 2131230751;
			
			// aapt resource value: 0x7f080023
			public const int q_description = 2131230755;
			
			// aapt resource value: 0x7f080020
			public const int q_parameter = 2131230752;
			
			// aapt resource value: 0x7f080054
			public const int read_and_write_activity = 2131230804;
			
			// aapt resource value: 0x7f080055
			public const int read_and_write_address_label = 2131230805;
			
			// aapt resource value: 0x7f08005d
			public const int read_and_write_ascii_input = 2131230813;
			
			// aapt resource value: 0x7f08005b
			public const int read_and_write_bank_label = 2131230811;
			
			// aapt resource value: 0x7f080057
			public const int read_and_write_bank_prompt = 2131230807;
			
			// aapt resource value: 0x7f080056
			public const int read_and_write_init_address_label = 2131230806;
			
			// aapt resource value: 0x7f08005c
			public const int read_and_write_note = 2131230812;
			
			// aapt resource value: 0x7f080059
			public const int read_and_write_password_edittext = 2131230809;
			
			// aapt resource value: 0x7f08005a
			public const int read_and_write_password_label = 2131230810;
			
			// aapt resource value: 0x7f080058
			public const int read_and_write_read_button = 2131230808;
			
			// aapt resource value: 0x7f080053
			public const int read_and_write_title_label = 2131230803;
			
			// aapt resource value: 0x7f08005e
			public const int read_and_write_write_button = 2131230814;
			
			// aapt resource value: 0x7f080010
			public const int reader_configuration_item = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int reader_image = 2131230735;
			
			// aapt resource value: 0x7f080031
			public const int red = 2131230769;
			
			// aapt resource value: 0x7f08000a
			public const int refresh_button = 2131230730;
			
			// aapt resource value: 0x7f080078
			public const int rt0005_battery_status = 2131230840;
			
			// aapt resource value: 0x7f080071
			public const int rt0005_ctrl_room = 2131230833;
			
			// aapt resource value: 0x7f080074
			public const int rt0005_est_time_arrival = 2131230836;
			
			// aapt resource value: 0x7f080073
			public const int rt0005_histogram_alarm = 2131230835;
			
			// aapt resource value: 0x7f080077
			public const int rt0005_mean_kinetic_temp = 2131230839;
			
			// aapt resource value: 0x7f080075
			public const int rt0005_mem_full = 2131230837;
			
			// aapt resource value: 0x7f08007b
			public const int rt0005_refresh_state_button_caption = 2131230843;
			
			// aapt resource value: 0x7f080076
			public const int rt0005_rem_shelf_life = 2131230838;
			
			// aapt resource value: 0x7f080079
			public const int rt0005_shipping_date = 2131230841;
			
			// aapt resource value: 0x7f08007a
			public const int rt0005_stop_date = 2131230842;
			
			// aapt resource value: 0x7f080072
			public const int rt0005taglabel = 2131230834;
			
			// aapt resource value: 0x7f08007f
			public const int saveButtonText = 2131230847;
			
			// aapt resource value: 0x7f080026
			public const int session1_note = 2131230758;
			
			// aapt resource value: 0x7f080027
			public const int session2_note = 2131230759;
			
			// aapt resource value: 0x7f080028
			public const int session3_note = 2131230760;
			
			// aapt resource value: 0x7f080029
			public const int session4_note = 2131230761;
			
			// aapt resource value: 0x7f080025
			public const int session_description = 2131230757;
			
			// aapt resource value: 0x7f080032
			public const int session_note = 2131230770;
			
			// aapt resource value: 0x7f080024
			public const int session_parameter = 2131230756;
			
			// aapt resource value: 0x7f080046
			public const int start_byte_mask_label = 2131230790;
			
			// aapt resource value: 0x7f080044
			public const int target_ascii_mask_checkbox = 2131230788;
			
			// aapt resource value: 0x7f080043
			public const int target_both_match_radaiobutton = 2131230787;
			
			// aapt resource value: 0x7f08003e
			public const int target_by_mask_radiobutton = 2131230782;
			
			// aapt resource value: 0x7f08003d
			public const int target_by_select_tag_radiobutton = 2131230781;
			
			// aapt resource value: 0x7f080040
			public const int target_end_with_radiobutton = 2131230784;
			
			// aapt resource value: 0x7f080041
			public const int target_match_radiobutton = 2131230785;
			
			// aapt resource value: 0x7f080042
			public const int target_not_match_radiobutton = 2131230786;
			
			// aapt resource value: 0x7f080045
			public const int target_selected_ascii_checkbox = 2131230789;
			
			// aapt resource value: 0x7f08003f
			public const int target_start_with_radiobutton = 2131230783;
			
			// aapt resource value: 0x7f080005
			public const int tcp_cancel = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int tcp_confirm = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int tcp_label = 2131230723;
			
			// aapt resource value: 0x7f08007d
			public const int titleFileDialog = 2131230845;
			
			// aapt resource value: 0x7f08006a
			public const int title_activity_kill_tag = 2131230826;
			
			// aapt resource value: 0x7f08005f
			public const int title_activity_lock_tag = 2131230815;
			
			// aapt resource value: 0x7f080051
			public const int title_activity_main = 2131230801;
			
			// aapt resource value: 0x7f080052
			public const int title_activity_read_and__write = 2131230802;
			
			// aapt resource value: 0x7f080013
			public const int todo = 2131230739;
			
			// aapt resource value: 0x7f08000b
			public const int total_found = 2131230731;
			
			// aapt resource value: 0x7f080030
			public const int yellow = 2131230768;
			
			// aapt resource value: 0x7f080015
			public const int zero = 2131230741;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int inventory_button_style = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
